steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'create', 'n1-nano-vm', '--image-family', 'debian-11', '--image-project', 'debian-cloud', '--zone', 'europe-west3-c', '--boot-disk-size', '10GB', '--create-disk', 'mode=rw,size=100GB', '--no-address']
  env:
    PROJECT_ID: 'extreme-zephyr-318408'
