steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'compute', 'regions', 'set-policy', 'europe-west3', '--restriction=europe-west3']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'billing', 'budget', 'create', 'budget-for-services', '--amount=500', '--display-name=Monthly-Budget-for-Services', '--period=MONTHLY']
