# Set project ID
PROJECT_ID=extreme-zephyr-318408

# Create Compute Engine instance
gcloud compute instances create vm-instance \
  --project=$PROJECT_ID \
  --zone=europe-west3-c \
  --machine-type=n1-nano \
  --image-family=debian-11 \
  --boot-disk-size=10GB \
  --boot-disk-type=pd-standard \
  --create-disk=mode=none,type=pd-standard,size=100GB \
  --no-address \
  --metadata=google-logging-enabled=true

